[package]
name = "guessting_game"
version = "0.1.0"
edition = "2018"
authors = ["Kien Knot <itotaka523@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
